
EXCEL_OUTPUT = "Result.xlsx"

# Названия колонок в выходном Excel 
DESIRED_COLUMNS = [
    "DOT Status",
    "Operating Status",
    "Entity Type",
    "DBA Name",
    "MC/MX/FF",
    "Name",
    "Added",
    "DOT#",
    "Physical Address",
    "Mailing Address",
    "Phone",
    "Cell",
    "Contact Name",
    "Fax",
    "Email",
    "Total Number of Power Units",
    "Total Number of Trucks",
    "Total Number of Tractors",
    "Trailer",
    "MCS-150 date",
    "MCS-150 Mileage (Year)",
    "MCS-150 Mileage",
    "TypeInsurance",
    "Carrier",
    "Policy/Surety",
    "Coverage",
    "Effective Date",
    "Cancellation Date",
    "Insurance2 Type",
    "Insurance2 Carrier",
    "Insurance2 Policy/Surety",
    "Insurance2 Coverage",
    "Insurance2 Effective Date",
    "Insurance2 Cancellation Date",
    "Insurance3 Type",
    "Insurance3 Carrier",
    "Insurance3 Policy/Surety",
    "Insurance3 Coverage",
    "Insurance3 Effective Date",
    "Insurance3 Cancellation Date",
    "Drivers_Interstate_within_100_miles",
    "Drivers_Interstate_beyond_100_miles",
    "Drivers_Interstate_Total",
    "Drivers_Intrastate_within_100_miles",
    "Drivers_Intrastate_beyond_100_miles",
    "Drivers_Intrastate_Total",
    "Drivers_Avg_num_trip_leased_drivers_month",
    "Drivers_Grand_Total",
    "Drivers_Total_with_Commercial_Drivers_License",
    "Cargo Transported"
]

# переименовка  полей из census
CENSUS_MAPPING = {
    "status_code":                  "DOT Status",
    "carrier_operation":            "Operating Status",
    "business_org_desc":            "Entity Type",
    "dba_name":                     "DBA Name",
    "dot_number":                   "DOT#",
    "legal_name":                   "Name",
    "add_date":                     "Added",
    "phy_street":                   "Physical Address (Street)",
    "phy_city":                     "Physical Address (City)",
    "phy_state":                    "Physical Address (State)",
    "phy_zip":                      "Physical Address (ZIP)",
    "carrier_mailing_street":       "Mailing Address (Street)",
    "carrier_mailing_city":         "Mailing Address (City)",
    "carrier_mailing_state":        "Mailing Address (State)",
    "carrier_mailing_zip":          "Mailing Address (ZIP)",
    "phone":                        "Phone",
    "cell_phone":                   "Cell",
    "company_officer_1":            "Contact Name",
    "fax":                          "Fax",
    "email_address":                "Email",
    "power_units":                  "Total Number of Power Units",
    "owntruck":                     "Total Number of Trucks",
    "owntract":                     "Total Number of Tractors",
    "owntrail":                     "Trailer",
    "mcs150_date":                  "MCS-150 date",
    "mcs150_mileage_year":          "MCS-150 Mileage (Year)",
    "mcs150_mileage":               "MCS-150 Mileage",
    "interstate_within_100_miles":  "Drivers_Interstate_within_100_miles",
    "interstate_beyond_100_miles":  "Drivers_Interstate_beyond_100_miles",
    "driver_inter_total":           "Drivers_Interstate_Total",
    "intrastate_within_100_miles":  "Drivers_Intrastate_within_100_miles",
    "intrastate_beyond_100_miles":  "Drivers_Intrastate_beyond_100_miles",
    "total_intrastate_drivers":     "Drivers_Intrastate_Total",
    "avg_drivers_leased_per_month": "Drivers_Avg_num_trip_leased_drivers_month",
    "total_drivers":                "Drivers_Grand_Total",
    "total_cdl":                    "Drivers_Total_with_Commercial_Drivers_License",
}

# Флаги cargo 
CARGO_FLAGS = [
    "crgo_genfreight", "crgo_household", "crgo_metal", "crgo_motorveh", "crgo_driveaway",
    "crgo_logs", "crgo_bldgmat", "crgo_machinery", "crgo_freshprod", "crgo_liqgas",
    "crgo_intermodal", "crgo_oilfield", "crgo_livestock", "crgo_grainhay", "crgo_coal",
    "crgo_meat", "crgo_garbage", "crgo_usmail", "crgo_beverages", "crgo_paper",
    "crgo_utilities", "crgo_agfarm", "crgo_construct", "crgo_waterwell", "crgo_other",
    "crgo_chem"
]